local_people/board/urls.py
from django.urls import path

from . import views

app_name="board"
urlpatterns = [
    path("list/", views.list, name="list"), 
]

local_people/common/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name = 'login' ),
    path('logout/', auth_views.LoginView.as_view(), name = 'logout' ),
    path('signup/', views.signup, name='signup'),
]

local_people/config/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    # path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('member/', include('member.urls')),
    path('common/', include('common.urls')),
]

local_people/member/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'member'

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name='login'),
    path('logout/',views.logout, name='logout'),
]

local_people/board/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    title = models.CharField(max_length=100)
    writer = models.CharField(max_length=100)
    contents = models.TextField()
    wdate = models.DateTimeField()
    hit = models.IntegerField()

local_people/common/models.py
from django.db import models

# Create your models here.

local_people/member/models.py
from django.db import models



# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=64,verbose_name = '사용자명')
    password = models.CharField(max_length=64,verbose_name = '비밀번호')
    registered_dttm = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')  

    def __str__(self): # 이 함수 추가
        return self.username  # User object 대신 나타낼 문자 


    class Meta: #메타 클래스를 이용하여 테이블명 지정
            db_table = 'member_member'

local_people/board/views.py
from django.shortcuts import render
from .models import Board
# Create your views here.
def list(request):
    print("")
    # boardList = Board.objects.all()
    # boardList = Board.objects.order_by('-id')
    # return render(request, "board/board_list.html", {'boardList':boardList} )

def create(request):
    board = Board() 
    board.title = request.GET['title']
    board.writer = request.GET['writer']
    board.contents = request.GET['contents']
    board.save()
    return

#조회 
#queryset = 모델 클래스명.objects.all()
#queryset = queryset.filter(조건필드1 = 조건값1, 조건필드2 = 조건값2)
#queryset = queryset.filter(조건필드3 = 조건값3)
#question_list = Board.objects.order_by('-wdate')
#print(connection)
#mysql -u root -p --port = 5036

import pymysql
conn = pymysql.connect(host = 'localhost', user = 'user01', password =
'1234' ,db = 'mydb', port=5306)
curs = conn.cursor()
sql = "SELECT 1 id, title, writer, date_format(wdate, '%Y-%m-%d') wdate, contents, hit+10 hit FROM board_board"
curs.execute(sql) # 쿼리문 실행

rows = curs.fetchall() # 데이터 패치
for row in rows :
    print(row)
conn.close()

local_people/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login 


from .forms import UserForm

# Create your views here.

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save() 
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
        else:
            form = UserForm()
        return render(request, 'common/signup.html', {'form':form})

local_people/member/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password
from .models import User

# Create your views here.

#회원가입 ; 등록 

def register(request):   #회원가입 페이지를 보여주기 위한 함수
    if request.method == "GET":
        return render(request, 'users/register.html')

    elif request.method == "POST":
        username = request.POST.get['username',None]   #딕셔너리형태
        password = request.POST.get['password',None]
        re_password = request.POST.get['re_password',None]
        res_data = {} 
        if not (username and password and re_password) :
            res_data['error'] = "모든 값을 입력해야 합니다."
        if password != re_password :
            # return HttpResponse('비밀번호가 다릅니다.')
            res_data['error'] = '비밀번호가 다릅니다.'
        else :
            user = User(username=username, password= make_password(password))
            user.save()
        return render(request, 'users/register.html', res_data) #register를 요청받으면 register.html 로 응답.
    

# 로그인 ; LOGIN
def login(request):
    if request.method == 'GET':
        return render(request, 'users/login.html')  
    
    elif request.method == "POST":
        username = request.POST['username']  #form의 name
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('board:list'))
        
        else:
            return render(request, '/index.html')
        
import sqlite3
con = sqlite3.connect(":memory:")
cur = con.cursor()
cur.execute("CREATE TABLE PhoneBook(Name text, PhoneNum text);")
cur.execute("INSERT INTO PhoneBook VALUES('Derick', '010-1234-5678');")

cur.execute("SELECT * FROM PhoneBook;")
for row in cur:
    print(row)

local_people/service/views.py
from django.shortcuts import render

# Create your views here.

local_people/templates/Users/board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

local_people/templates/Users/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

local_people/templates/Users/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

local_people/templates/Users/map.html
<!DOCTYPE html>
<html>
  <head>
    <title>W3.CSS Template</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- 카카오맵 -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=1402673160ece216db7b03592305e6a4"></script>
    <!-- services와 clusterer, drawing 라이브러리 불러오기 -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=1402673160ece216db7b03592305e6a4&libraries=services,clusterer,drawing"></script>
    <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
    .myLink {display: none}
    </style>
  </head>
<body class="w3-light-grey">

<!-- Navigation Bar -->

<div class="w3-bar w3-white w3-border-bottom w3-large">
    <a href="#" class="w3-bar-item w3-button w3-text-red w3-hover-red"><b><i class="fa fa-map-marker w3-margin-right"></i>LocalPeople</b></a>
    <nav class="navbar navbar-expand justify-content-end">
        <div class="container-fluid">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'member:register' %}">회원가입</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'member:login' %}">로그인</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'member:list' %}">게시판</a>
                </li>
            </ul>
        </div>

        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="어디어디 맛집">
            <a href="#" class="search-button w3-bar-item w3-button w3-right w3-hover-red w3-text-grey"><i class="fa fa-search"></i></a>    
        </div>
        
    </nav>

</div>
<!-- 네비게이션바 -->
<!-- 지도 -->
<div id="map" style="width:100%;height:350px;"></div>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=1402673160ece216db7b03592305e6a4&libraries=services"></script>
<script>
    

    // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
    var infowindow = new kakao.maps.InfoWindow({zIndex:1});

    var mapContainer = document.getElementById('map');
    var mapOption = {
        center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
        level: 4 // 지도의 확대 레벨
    };  

    // 지도 생성 
    var map = new kakao.maps.Map(mapContainer, mapOption);
    // 장소 검색 객체를 생성합니다
    var ps = new kakao.maps.services.Places();
    // 장소 키워드 검색 입력값 받기 
    var searchBtn = document.querySelector('.search-button');
    var psValue;

    searchBtn.addEventListener('click', function() {
        psValue = document.querySelector('.form-control').value;
        console.log(psValue);
        ps.keywordSearch('이태원 맛집', placesSearchCB); // 검색 요청을 클릭 이벤트 핸들러 함수 내부로 이동
    });

    // 키워드 검색시 호출되는 콜백함수 
    function placesSearchCB(data, status, pagination) {
        if (status === kakao.maps.services.Status.OK) {
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
            // LatLngBounds 객체에 좌표를 추가합니다
            var bounds = new kakao.maps.LatLngBounds();

            for (var i = 0; i < data.length; i++) {
                displayMarker(data[i]);
                bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
            }

            // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
            map.setBounds(bounds);
        }
    }
</script>
</body>

</html>

local_people/templates/Users/register.html
<html>
    
    <head>
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    </head>
    <body>
        <div class= "container">
            <div class = "row mt-5">
                <div class = "col-12 text-center">
                    <h1>회원가입</h1>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
        
        <!--            폼 안에다가 입력해줘야한다. (안써주면 에러발생)
             csrf_token 폼의 경우에는 , 데이터를 서버에 전달하는 기능.이때 암호화된 키를 숨겨놓아 크로스도메인을 막기 위함. -->
    <!-- bootstrap -component - forms -->
              <div class= "container">
                <div class = "row mt-5">
                    {{error}}
                    <div class = "col-12 ">
            <div class = "row mt-5">
                <div class = "col-12 ">
                    <form method = "POST" action = ".">  
                    {% csrf_token %} 
    <div class="form-group">
      <label for="username">사용자 이름</label>
      <input 
      type="text" 
      class="form-control" 
      id="username" 
      placeholder="사용자 이름"
      name="username">   
      <!-- 이 name 값으로 정보가 전달된다 -->
    </div>

    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" 
      class="form-control"
       id="password"
        placeholder="비밀번호"
        name= "password">
    </div>
    
    <div class="form-group">
      <label for="re_password">비밀번호 확인</label>
      <input 
      type= "password" 
      class="form-control"
       id="re_password"
        placeholder="비밀번호 확인"
        name = "re_password">
    </div>
    <button type="submit" class="btn btn-primary">등록</button>
    </form>    


</body>
</html>

local_people/templates/Users/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>